# inventory.yaml - Ansible inventory file for managing the target host
all:
  hosts:
    #"{{ lookup('ansible.builtin.env', 'TARGET_IP', default='10.160.240.70') }}":
    "{{ lookup('ansible.builtin.env', 'TARGET_IP') }}":
      #ansible_user:  "{{ lookup('ansible.builtin.env', 'ANSIBLE_USER', default='orangepi') }}"
      ansible_user:  "{{ lookup('ansible.builtin.env', 'ANSIBLE_USER') }}"
      ansible_become: yes
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3



